[PROTOCOLS]
Protocols SPA = [
	{"tag": "section", "text": "2D", "children": [
		{"tag": "protocol_group", "text": "Classify", "openItem": "False", "children": [
			{"tag": "protocol", "value": "ProtSimpleAbInitio2D", "text": "default"}
		]}
	]},
	{"tag": "section", "text": "3D", "children": [
		{"tag": "protocol_group", "text": "Initial volume", "openItem": "False", "children": [
			{"tag": "protocol", "value": "ProtSimpleAbInitio3D", "text": "default"}
		]},
		{"tag": "protocol_group", "text": "Refine", "openItem": "False", "children": [
			{"tag": "protocol", "value": "ProtSimpleNURef3D", "text": "default"}
		]},
		{"tag": "protocol_group", "text": "Analysis", "openItem": "False", "children": [
			{"tag": "section", "text": "more", "openItem": "False", "children": [
				{"tag": "protocol", "value": "ProtSimpleSymmetryTest", "text": "default"}
			]}
		]}
	]}
]
